### ISSUE TITLE
Fix docs regarding filtering

### ISSUE THREAD

**Issue by ifeanyiisitor** [Financial-Times/athloi#18]
Filtering in the following ways don't work: 
- **a)** `athloi run build --filter scope:anvil`
- **b)** `athloi run build --filter scope:"anvil"`

But filtering like this works: 

- **c)**  `athloi run build --filter scope:'"anvil"'`

This is however not accurately documented in the README. 
As an aside, it seems that the intention is for mechanism **b** but this is not the case.

See: https://github.com/Financial-Times/athloi/blob/master/src/filter-packages.js#L6

**Comment by i-like-robots** [comment]
I understand this is due to the way arguments are parsed by the OS. Quotation marks will always be evaluated (the rules of which are unclear to me but if `"foo"` or `'foo'` goes in then `foo` will come out!).

Athloi currently coerces the `--filter` option using `JSON.parse()` so string values do need to be quoted as you mention.

But this does mean to use quotes - and for Athloi to receive them - they must be escaped or encapsulated within other quotes just like you mention, e.g. `--filter 'scope:"anvil"'` or `--filter scope:\"anvil\"`.

I think there are two possible ways we can handle this:

1. Continue to use `JSON.parse()` but add examples using string values to the readme
2. We stop using `JSON.parse()` and implement a basic algorithm to coerce only boolean or number values and assume everything else is a string, e.g. `--filter scope:anvil`

What do you think @quarterto?
